accounts/urls.py
from unicodedata import name
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('register',views.RegistrationView.as_view(),name='register'),
    path('login',views.AccountLoginView.as_view(),name='login'),
    path('logout',views.AccountLogoutView.as_view(),name='logout')
]

kantin_kejujuran/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('store.urls','store'),namespace='store',)),
    path('account/',include(('accounts.urls','accounts'),namespace='accounts'))

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.StoreView.as_view(),name="home"),
    path('<int:id>',views.DetailStoreView.as_view(),name="detail_item"),
    path('items',views.GetItemView.as_view(),name='get_items'),
    path('create',views.CreateItemView.as_view(),name='create_item'),
    path('items/<int:id>',views.GetDetailItemView.as_view(),name='detail_item_api'),
    path('items/delete/<int:id>',views.DeleteDetailItemView.as_view(),name='delete_item_api'),
    path('balance',views.BalanceBoxView.as_view(),name='balance_box'),
    path('balance_box',views.GetBalanceBoxView.as_view(),name="get_balance_box"),
    path('balance_box/increment',views.IncreaseBalanceBoxView.as_view(),name="increment_balance_box"),
    path('balance_box/decrement',views.DecreaseBalanceBoxView.as_view(),name="decrement_balance_box"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,PermissionsMixin,AbstractUser
from .validators import validate_student_id
from .managers import UserManager

class User(AbstractBaseUser,PermissionsMixin):
    student_id = models.CharField(max_length=5,unique=True,validators=[validate_student_id])
    date_joined = models.DateTimeField(auto_now_add=True)
    is_staff = models.BooleanField(default=False)
    objects = UserManager()

    USERNAME_FIELD = 'student_id'
    

    

        

store/models.py
from datetime import datetime
from django.db import models
from solo.models import SingletonModel

# Create your models here.
class Item(models.Model):
    name = models.CharField(max_length=30)
    image = models.ImageField(upload_to="images")
    desc = models.CharField(max_length=100)
    price = models.PositiveIntegerField()
    date = models.DateTimeField(auto_now_add=True, blank=True)

class BalanceBox(SingletonModel):
    balance = models.PositiveBigIntegerField(default=0)

    def __str__(self):
        return "Balance Box"

    class Meta:
        verbose_name = "Balance Box"

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import User

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('student_id',)

store/forms.py
from .serializers import BalanceBoxSerializer, IncreaseBalanceBoxAmountSerializer,DecreaseBalanceBoxAmountSerializer
from drf_braces.forms.serializer_form import SerializerForm
from django.forms import ModelForm, forms
from .models import BalanceBox, Item

class BalanceBoxForm(ModelForm):
    def __init__(self,*args,**kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
    class Meta:
        model = BalanceBox
        fields = '__all__'

class ItemForm(ModelForm):
    def __init__(self,*args,**kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
    class Meta:
        model = Item
        fields = '__all__'

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.views import LoginView,LogoutView
from django.urls import reverse_lazy
from .forms import CustomUserCreationForm
# Create your views here.
class RegistrationView(SuccessMessageMixin,CreateView):
    template_name = 'registration.html'
    success_url = reverse_lazy('accounts:login')
    form_class = CustomUserCreationForm
    success_message = "Your profile was created successfully"

class AccountLoginView(LoginView):
    template_name = 'login.html'
    next_page = reverse_lazy('store:home')

class AccountLogoutView(LogoutView):
    next_page = reverse_lazy('accounts:login')

    

store/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView,DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from rest_framework.generics import CreateAPIView, ListAPIView, RetrieveAPIView, UpdateAPIView, DestroyAPIView
from rest_framework.filters import OrderingFilter
from .models import BalanceBox, Item
from .serializers import BalanceBoxSerializer, DecreaseBalanceBoxAmountSerializer, IncreaseBalanceBoxAmountSerializer, ItemSerializer
from .forms import ItemForm,BalanceBoxForm
from rest_framework.authentication import SessionAuthentication
from rest_framework.permissions import IsAuthenticated

class CreateItemView(CreateAPIView):
    serializer_class = ItemSerializer
    authentication_classes = [SessionAuthentication]
    permission_classes = [IsAuthenticated]

class GetItemView(ListAPIView):
    serializer_class = ItemSerializer
    queryset = Item.objects.all()
    filter_backends = [OrderingFilter]
    ordering_fields = ['name', 'date']
    ordering = ['name']


class GetDetailItemView(RetrieveAPIView):
    serializer_class = ItemSerializer
    queryset = Item.objects.all()
    lookup_url_kwarg = "id"

class DeleteDetailItemView(DestroyAPIView):
    serializer_class = ItemSerializer
    authentication_classes = [SessionAuthentication]
    permission_classes = [IsAuthenticated]
    queryset = Item.objects.all()
    lookup_url_kwarg = "id"

class GetBalanceBoxView(RetrieveAPIView):
    serializer_class = BalanceBoxSerializer
    authentication_classes = [SessionAuthentication]
    permission_classes = [IsAuthenticated]

    def get_object(self):
        obj = BalanceBox.get_solo()
        return obj

class UpdateBalanceBoxView(UpdateAPIView):
    serializer_class = BalanceBoxSerializer
    authentication_classes = [SessionAuthentication]
    permission_classes = [IsAuthenticated]
    def get_object(self):
        obj = BalanceBox.get_solo()
        return obj

class IncreaseBalanceBoxView(UpdateBalanceBoxView):
    serializer_class = IncreaseBalanceBoxAmountSerializer

class DecreaseBalanceBoxView(UpdateBalanceBoxView):
    serializer_class = DecreaseBalanceBoxAmountSerializer
    
class StoreView(TemplateView):
    template_name = 'index.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['itemForm'] = ItemForm()
        return context

class DetailStoreView(DetailView):
    model = Item
    template_name = 'detail_item.html'
    pk_url_kwarg = 'id'

class BalanceBoxView(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy('accounts:login')
    template_name = 'balance_box.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['increaseBalanceForm'] = BalanceBoxForm()
        context['decreaseBalanceForm'] = BalanceBoxForm()
        return context

accounts/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block main %} 
    <div class="container px-4 px-lg-5 m-3">
        <div class="row gx-4 gx-lg-5">
            <div class="col">
                <h1 class="h1">Login Form</h1>
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}                    
                    <button class="btn btn-primary mt-2" type="submit">Login</button>
                </form>
            </div>
        </div>
    </div>
    <script>
		$(document).ready(function(){
			$('#loginNav').addClass('active')
		})
	</script>
{% endblock %} 

accounts/templates/registration.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block main %} 
	<div class="container px-4 px-lg-5 m-3">
		<div class="row gx-4 gx-lg-5">
			<div class="col">
				<h1 class="h1">Registration Form</h1>
				<form method="POST">
					{% csrf_token %}
					{{ form|crispy }}                    
					<button class="btn btn-primary" type="submit">Register</button>
				</form>
			</div>
		</div>
	</div>
	<script>
		$(document).ready(function(){
			$('#registerNav').addClass('active')
		})
	</script>


{% endblock %} 

store/templates/balance_box.html
{% extends 'base.html' %}
{% load static %}
{% block head_extend %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
    <script src="https://malsup.github.io/jquery.form.js"></script> 
{% endblock %}
{% block main %}
    <header class="bg-dark py-5">
        <div class="container px-1 px-lg-2 my-2">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Current Balance Box</h1>
                <h2 class="h2" id="balanceCurrency"></h2>
            </div>
        </div>
    </header>
    <!-- <div class="row gx-4 gx-lg-5 justify-content m-2">
        <div class="col">
            <h1 class="h1">Current Balance Box</h1>
            <h2 class="h2" id="balanceCurrency"></h2>
        </div>
    </div> -->
    <div class="row gx-4 gx-lg-5 row-cols-2  m-2">
        <div class="col justify-content-center">
            <h3 class="h3 text-center">Deposit Form</h3>
            <form id="increaseForm" action="{% url 'store:increment_balance_box' %}" method="post">
                {{increaseBalanceForm.as_p}}
                <input type="submit" class="btn btn-primary btn-block" value="Deposit">
            </form>   
        </div>
        <div class="col justify-content-center">
            <h3 class="h3 text-center">Withdrawal Form</h3>
            <form id="decreaseForm" action="{% url 'store:decrement_balance_box' %}">
                {{decreaseBalanceForm.as_p}}
                <input type="submit" class="btn btn-primary btn-block" value="Withdraw">
            </form>
        </div>
    </div>
    <script>
        $(document).ready(function(){
            $('#balanceBoxNav').addClass('active')
            var url = "{% url 'store:get_balance_box' %}"
            $.ajax({
                url: url,
                type: 'GET',
                dataType: 'json', 
                success: function(res){
                    $('#balanceCurrency').html(`Rp.${addCommas(res.balance)},-`)
                }
            })
        });
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        $("#increaseForm, #decreaseForm").submit(function(e){
                e.preventDefault(); 

                var form = $(this);
                var actionUrl = form.attr('action');
                const csrftoken = getCookie('csrftoken');
                if ($(this).attr('id') == "increaseForm"){
                    var title = 'Deposit Confirmation'
                    var content = 'Are you sure you wanna deposit to the balance box?'
                    var alert_text = "Money successfully deposited to balance box!"
                }
                else{
                    var title = 'Withdrawal Confirmation'
                    var content = 'Are you sure you wanna withdraw from the balance box?'
                    var alert_text = "Successfully withdraw money from balance box!"
                }
                console.log(form.serialize());
                $.confirm({
                    title: title,
                    content: content,
                    buttons: {
                        Yes: function(){
                    $.ajax({
                        type: "PUT",
                        url: actionUrl,
                        data: form.serialize(), 
                        headers: {'X-CSRFToken': csrftoken},
                        success: function(data){
                            $.alert(alert_text)
                            $('#balanceCurrency').html(`Rp.${addCommas(data.balance)},-`);
                        },
                        error: function(xhr, status, error) {
                            var err = JSON.parse(xhr.responseText)
                            console.log(err.balance)
                            $.alert(err.balance[0]);
                        }
                    });
                        },
                        No: function(){

                        }
                    }
                })

            })

    </script>
{% endblock %}

store/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <title>Shop Homepage - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        {% block head_extend %}
        {% endblock %}

    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#!">Kantin Kejujuran</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item"><a id="storeNav" class="nav-link" aria-current="page" href="{% url 'store:home' %}">Store</a></li>
                        <li class="nav-item"><a id="balanceBoxNav" class="nav-link" href="{% url 'store:balance_box' %}">Balance Box</a></li>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        {% if request.user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link" href="#">{{request.user.student_id}}</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a></li>
                        {% else %}
                            <li class="nav-item"><a id="registerNav" class="nav-link" aria-current="page" href="{% url 'accounts:register' %}">Register</a></li>
                            <li class="nav-item"><a id="loginNav" class="nav-link" aria-current="page" href="{% url 'accounts:login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <div id="page-container">
            <div id="content-wrap">
                {% block main %}
                {% endblock %}
            </div>
        </div>
        <!-- Footer-->
        <footer class="footer py-5 bg-dark mt-auto fixed-bottom">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Compfest SEA 2022 WebChallenge </p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
        {% block script %}
        {% endblock %}
        <script>
            $(document).ready(function() {
                // Check if body height is higher than window height :)
                if ($(document).height() > $(window).height()) {
                    $('.footer').removeClass('fixed-bottom');
                }
            });
        </script>
    </body>
</html>

store/templates/detail_item.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
    <!-- Product section-->
    <section class="py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="row gx-4 gx-lg-5 align-items-center">
                <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{{item.image.url}}" alt="..." /></div>
                <div class="col-md-6">
                    <div class="small mb-1">{{item.date}}</div>
                    <h1 class="display-5 fw-bolder">{{item.name}}</h1>
                    <div class="fs-5 mb-5">
                        <span id="itemPrice">{{item.price}}</span>
                    </div>
                    <p class="lead">{{item.desc}}</p>

                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block script %}
    <script>
        $(document).ready(function(){
            $('#itemPrice').html(`Rp.${addCommas($('#itemPrice').html())},-`)
        })
    </script>
{% endblock %}

store/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block head_extend %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
    <script src="https://malsup.github.io/jquery.form.js"></script> 
{% endblock %}
{% block main %}
    <!-- Header-->
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Kantin Kejujuran</h1>
                <p class="lead fw-normal text-white-50 mb-0">Keep it simple and honest!</p>
            </div>
        </div>
    </header>
    <!-- Section-->
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                <div class="col mb-5 offset-1">
                    <h2 class="h2">Store Items</h2> 
                </div>
            </div>
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4">
                <div class="col mb-1 offset-1">
                    <div class="col offset-2 mb-3">
                        <h3 class="h3">Add Items</h3>
                        {% if request.user.is_authenticated %}
                        <button class="btn btn-primary" id="addItemButton">Click Me!</button>
                        <form id="addItemForm" style="display: none;" action="{% url 'store:create_item' %}" method="post">
                            {% csrf_token %}
                            {{itemForm}}
                            <input type="submit" class="btn btn-success" value="Add">
                            <button type="reset" id="addItemBackButton" class="btn btn-danger">Back</button>
                        </form>
                        {% else %}
                        <div class="alert alert-danger" role="alert">
                            Please log in to your students account to add items!
                        </div>
                        {% endif %}
                        
                    </div>
                </div>
            </div>
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4">
                <div class="col mb-1 offset-1">
                    <h3 class="h3 mx-5 ">Sort By</h3>
                </div>
            </div>

            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content">
                <div class="col mb-5 offset-1">
                        <select id="sortAtribute" class="form-select mx-5" aria-label="sort-by">
                            <option selected value="name">Name</option>
                            <option value="date">Date</option>
                        </select>
                        <select id="sortOrder" class="form-select mx-5 " aria-label="sort-order">
                            <option selected value="">Asc</option>
                            <option value="-">Desc</option>
                        </select>
                </div>
                <div class="col mb-5">
                    <button id="sortButton" class="btn btn-primary btn-block mx-5" value="">Sort!</a>
                </div>

            </div>
            <div id="card-rows" class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            </div>
        </div>
    </section>
    <script>
        function getItems(sort = ""){
            var urlItems = "{% url 'store:get_items' %}" + sort
            var urlBuy = "{% url 'store:delete_item_api' 0 %}"
            $.ajax({
                url: urlItems,
                type: 'GET',
                dataType: 'json', // added data type
                success: function(res) {
                    $("#card-rows").empty()
                    if (res.length == 0){
                        $("#card-rows").append(`<div class="alert alert-success" role="alert">
                            There are currently no items in the store
                        </div>`)
                    } else{
                        $.each(res,function(index,value){
                        $("#card-rows").append(`<div class=col mb-5> 
                            <div class="card h-100"> 
                                <img class="card-img-top" src="${value.image}"/> 
                                <div class="card-body p-4"> 
                                    <div class="text-center"> 
                                        <div class="small mb-1">${value.date.split('T')[0]}</div>
                                        <h5 class="fw-bolder">${value.name}</h5> 
                                        <p>Rp${addCommas(value.price)},-</p> 
                                    </div> 
                                </div> 
                                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent"> 
                                    <div class=text-center><a class="btn btn-outline-dark mt-auto" href="${value.id}">View Details</a></div>
                                    {% if request.user.is_authenticated %}
                                    <div class=text-center>
                                        <form class="buyForm" action="${urlBuy.replace(/0/,value.id.toString())}">
                                            <input type="submit" class="btn btn-primary" value="Buy">
                                        </form>
                                    </div> 
                                    {% endif %}
                                </div> 
                            </div> 
                        </div>`)
                        })
                    }
                    
                }
            });
        }
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        $(document).ready(function(){
            $('#storeNav').addClass('active')
            getItems();
            '{% if request.user.is_authenticated %}'
            $(document).on("submit", ".buyForm", function (e) {
                e.preventDefault()
                var form = $(this);
                var actionUrl = form.attr('action');
                const csrftoken = getCookie('csrftoken');
                $.confirm({
                    title: 'Buy Confirmation',
                    content: 'Are you sure you wanna buy this item?',
                    buttons: {
                        Yes: function(){
                            $.ajax({
                                url: actionUrl,
                                method: 'DELETE',
                                dataType: 'json',
                                headers: {'X-CSRFToken': csrftoken},
                                success: function(res){
                                    $.alert("Item successfully bought!")
                                    getItems();
                                },
                                error: function(xhr, status, error) {
                                    var err = eval("(" + xhr.responseText + ")");
                                    $.alert(err.Message);
                                }
                            })
                        },
                        No: function(){

                        }
                    }
                })
            });
            '{% endif %}'
        })
        '{% if request.user.is_authenticated %}'
        $("#addItemButton").click(function(){
            $(this).hide()
            $("#addItemForm").fadeIn();
        })
        $("#addItemBackButton").click(function(){
            $("#addItemForm").hide();
            $("#addItemButton").fadeIn();
        })
        $(".buyForm").on("submit",function(e){
            console.log("masuk");
            e.preventDefault();
            var form = $(this);
            var actionUrl = form.attr('action');
            const csrftoken = getCookie('csrftoken');
            $.confirm({
                title: 'Buy Confirmation',
                content: 'Are you sure you wanna buy this item?',
                buttons: {
                    Yes: function(){
                        $.ajax({
                            url: actionUrl,
                            method: 'DELETE',
                            dataType: 'json',
                            headers: {'X-CSRFToken': csrftoken},
                            success: function(res){
                                $.alert("Item successfully bought!")
                                getItems();
                            },
                            error: function(xhr, status, error) {
                                var err = eval("(" + xhr.responseText + ")");
                                $.alert(err.Message);
                            }
                        })
                    },
                    No: function(){

                    }
                }
            })
        })
        $("#addItemForm").submit(function(e){
            e.preventDefault();
            var form = $(this);
            var actionUrl = form.attr('action');
            const csrftoken = getCookie('csrftoken');
            $.confirm({
                title: 'Add Item Confirmation',
                content: 'Are you sure you wanna add this item?',
                buttons: {
                    Yes: function(){
                        form.ajaxSubmit({
                            success: function(res){
                                $.alert("Item successfully added!")
                                getItems();
                                
                            },
                            error: function(xhr, status, error) {
                                console.log(error);
                                console.log(status);
                                console.log(xhr);
                                $.alert(xhr.responseText);
                            }
                        })
                        // $.ajax({
                        //     url: actionUrl,
                        //     method: 'POST',
                        //     data: form.serialize(),
                        //     dataType: 'application/json',
                        //     processData: false,
                        //     contentType: false, 
                        //     headers: {'X-CSRFToken': csrftoken},
                        //     success: function(res){
                        //         $.alert("Item successfully added!")
                        //         getItems();
                        //     },
                            // error: function(xhr, status, error) {
                            //     console.log(error);
                            //     console.log(status);
                            //     console.log(xhr);
                            //     var err = eval("(" + xhr.responseText + ")");
                            //     $.alert(err.Message);
                            // }
                        // })
                    },
                    No: function(){

                    }
                }
            })
        })
        '{% endif %}'
        $("#sortButton").click(function(){
            var sortOrder = $("#sortOrder").val()
            var sortAtribute = $("#sortAtribute").val()
            var link = `?ordering=${sortOrder + sortAtribute}`
            getItems(link);
            
        });
    
    </script>
{% endblock %}